# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# we want to look like this http://www.kenwilliamschfc.com/
# in the templates via {{ site.myvariable }}.
title: Vashon Medicare Insurance | Vashon Medicare Maven
brand_name: MedicareMavenVashon
header:
  title: Vashon Island Medicare Maven
  subtitle: Medicare Supplemental Insurance made Simple!
mailto: "leeann@safesecuremoney.com"
mailto_url: "mailto:leeann@vashonmedicaremaven.com?subject=Seeking+Vashon+Medicare+Maven"
phone: "(206) 567-4600"
phone_url: "tel:+12065674600"
description: > # a simple web app launch site built using tachyons
url: "https://www.vashonmedicaremaven.com" # the base hostname & protocol for your site, e.g. http://example.com

social-icons:
  - title: Facebook
    url: https://facebook.com/TheBrownAgencyVashon
    class: facebook

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
